markdown: kramdown
title:
  primary: "INSPIRE - RSS 2025 Workshop on"
  secondary: "Informative Sensing and Planning for Intelligent Robotic Exploration"
description: "RSS 2025 X - Room, Los Angeles, US, 25th of June 2025, 08:15"
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

speakers:
  - name: Jen Jen Chung
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Associate Professor
    organization: The University of Queensland
    country: Australia
    url: https://scholar.google.com/citations?user=FpzRM5UAAAAJ&hl=en&oi=ao
  - name: Tara Javidi
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Professor
    organization: University of California San Diego
    country: USA
    url: https://tjavidi.eng.ucsd.edu/
  - name: Martin Saska
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Associate Professor
    organization: Czech Technical University in Prague
    country: Czech
    url: https://scholar.google.com/citations?user=5PBYoTsAAAAJ&hl=en&oi=ao
  - name: Nare Karapetyan
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Assistant Scientist
    organization: Woods Hole Oceanographic Institute (WHOI)
    country: USA
    url: https://scholar.google.com/citations?user=BvTFNTkAAAAJ&hl=en&oi=ao
  - name: Antonella Barišić Kulaš
    photo_url: /assets/images/speakers/placeholder.jpg
    role: PhD Student
    organization: University of Zagreb
    country: Croatia
    url: https://scholar.google.com/citations?user=ePnL9R4AAAAJ&hl=en&oi=ao
  - name: Lukas Schmid
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Postdoctoral research fellow
    organization: Massachusetts Institute of Technology
    country: USA
    url: https://scholar.google.com/citations?user=r79fGI0AAAAJ&hl=en&oi=ao
  - name: Ali-akbar Agha-mohammadi
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Robotics Technologist
    organization: NASA Jet Propulsion Laboratory
    country: USA
    url: https://scholar.google.com/citations?user=36qnUD4AAAAJ&hl=en&oi=ao
  - name: Hyondong Oh
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Associate Professor
    organization: Ulsan National Institute of Science and Technology
    country: South Korea
    url: https://scholar.google.com/citations?user=q_Pbm3kAAAAJ&hl=en
  - name: Shumon Koga
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Staff Engineer
    organization: Honda Research and Development
    country: Japan
    url: https://scholar.google.com/citations?user=5UMyBR8AAAAJ&hl=de&oi=ao
  - name: Marco Hutter
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Associate Professor
    organization: ETH Zurich
    country: Switzerland
    url: https://scholar.google.com/citations?user=DO3quJYAAAAJ&hl=de&oi=ao

panelists:
  - name: Jen Jen Chung
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Associate Professor
    organization: The University of Queensland
    country: Australia
  - name: Nare Karapetyan
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Assistant Scientist
    organization: Woods Hole Oceanographic Institute (WHOI)
    country: USA
    url: https://scholar.google.com/citations?user=BvTFNTkAAAAJ&hl=en&oi=ao

organizers:
  - name: Marija Popović
    photo_url: /assets/images/organizers/masha.jpg
    role: Assistant Professor
    organization: Delft University of Technology
    country: Netherlands
    url: https://google.com
  - name: Carlos Nieto-Granda
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Research Scientist
    organization: DEVCOM Army Research Laboratory
    country: USA
    url: https://google.com
  - name: Aamodh Suresh
    photo_url: /assets/images/speakers/placeholder.jpg
    role: Postdoctoral Fellow
    organization: DEVCOM Army Research Laboratory
    country: USA
    url: https://google.com
  - name: Julius Rückin
    photo_url: /assets/images/organizers/julius.jpg
    role: PhD Student
    organization: University of Bonn
    country: Germany
    url: https://google.com
  - name: Mykel Kochenderfer
    photo_url: /assets/images/organizers/mykel.jpg
    role: Associate Professor
    organization: Stanford University
    country: USA
    url: https://google.com
  - name: Muhammad Fadhil Ginting
    photo_url: /assets/images/organizers/fadhil.jpg
    role: PhD Student
    organization: Stanford University
    country: USA
    url: https://google.com

institutions:
  - name: TU Delft
    logo_url: /assets/images/institutions/delft_logo.svg
    url: https://www.tudelft.nl/
  - name: DEVCOM Army Research Laboratory
    logo_url: /assets/images/institutions/devcom_logo.png
    url: https://arl.devcom.army.mil/
  - name: University of Bonn
    logo_url: /assets/images/institutions/bonn_logo.jpeg
    url: https://www.uni-bonn.de/
  - name: PhenoRob
    logo_url: /assets/images/institutions/phenorob_logo.jpg
    url: https://www.phenorob.de/
  - name: Stanford University
    logo_url: /assets/images/institutions/stanford_logo.png
    url: https://www.stanford.edu/
  - name: ICRA 2025
    logo_url: /assets/images/institutions/rss_logo.png
    url: https://2025.ieee-icra.org/

call:
  topics:
    - Multi-modal sensing
    - Multi-sensor fusion
    - Real-time uncertainty estimation
    - Online mapping
    - Novel information metrics
    - Real-time communication and data sharing
    - Learning-based methods for planning
    - Coordinated information gathering
    - Persistent environmental monitoring
    - Behavioral reasoning
    - Active simultaneous localization and mapping
    - Planning for active learning
    - Transfer learning across tasks or application domains
    - Real-world deployment of information gathering frameworks
    - ...
  submissions:
    url: "#submissions"
    link_name: TBC
events:
  - name: Workshop contribution submission deadline
    date: May 5 2025
  - name: Notification of acceptance
    date: May 17 2025
  - name: Full-day workshop
    date: June 25 2025